server:
  port: 8080
#  servlet:
#    context-path: /community-app-api

spring:
  application:
    name: community-app-backend
  profiles:
    active: dev
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB # 单个上传⽂件⼤⼩限定为10M
      max-request-size: 100MB # 单次上传⽂件⼤⼩限定为100M

  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      base-url: https://dashscope.aliyuncs.com
      read-timeout: 8000 # 读取超时时间，默认 8 秒
      chat:
        options:
          model: qwen-plus
          #          model: qwen-vl-max-latest
          # 基础参数：压缩计算量
          temperature: 0.2  # 设置输出随机性为中等程度
          seed: 123456  # 固定种子，避免重复推理
          top_p: 0.6 # 收集采样范围，加速解码
          top_k: 30 # 限制候选词数量
          max-tokens: 2000  # 控制输出长度
          repetition_penalty: 1.1 # 轻度去重，避免废话
          # 流式输出
          stream: true
          response_format: { type: "text" }
          tool-choice: "auto"

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: top.xym.*.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: true
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  config: classpath:log/logback-spring.xml

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: top.xym.community.app.controller

# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true
    username: admin
    password: 123456

auth:
  valid_urls:
    - /auth/logout
    - /user/**
    - /resource/publish

aliyun:
  oss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    accessKeyId: LTAI5tQnFUmsUb2gMFdE7W2d
    accessKeySecret: McFDTO4w3onWHaSBjKSnFr05IfQShq
    bucketName: mxy-u
    temp-dir: temp/qa-image
    url-expire: 1800
    max-file-size: 5MB
    allowed-types: jpg,jpeg,png,gif

share:
  sms:
    ccp:
      serverIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c9035ff9f0192adc3c9217d46
      accountToken: b45e565c34a844d3848b0f86a88c5a25
      appId: 2c94811c9035ff9f0192adc3ca9a7d4d
      templateId: 1

jwt:
  secret: community-app-2026-secure-key-123456
  expiration: 86400000  # 1天，毫秒